DOTNET DEV/ArnaudCore/ArnaudCore/Controllers/CarCoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ArnaudCore.Data;
using ArnaudCore.Models;

namespace ArnaudCore.Controllers
{
    public class CarCoresController : Controller
    {
        private readonly GarageFactory _context;

        public CarCoresController(GarageFactory context)
        {
            _context = context;    
        }

        // GET: CarCores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cars.ToListAsync());
        }

        // GET: CarCores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carCore = await _context.Cars
                .SingleOrDefaultAsync(m => m.ID == id);
            if (carCore == null)
            {
                return NotFound();
            }

            return View(carCore);
        }

        // GET: CarCores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CarCores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Model,MaxSpeed")] CarCore carCore)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carCore);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(carCore);
        }

        // GET: CarCores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carCore = await _context.Cars.SingleOrDefaultAsync(m => m.ID == id);
            if (carCore == null)
            {
                return NotFound();
            }
            return View(carCore);
        }

        // POST: CarCores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Model,MaxSpeed")] CarCore carCore)
        {
            if (id != carCore.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carCore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarCoreExists(carCore.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(carCore);
        }

        // GET: CarCores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carCore = await _context.Cars
                .SingleOrDefaultAsync(m => m.ID == id);
            if (carCore == null)
            {
                return NotFound();
            }

            return View(carCore);
        }

        // POST: CarCores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carCore = await _context.Cars.SingleOrDefaultAsync(m => m.ID == id);
            _context.Cars.Remove(carCore);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CarCoreExists(int id)
        {
            return _context.Cars.Any(e => e.ID == id);
        }
    }
}

DOTNET DEV/ArnaudCore/ArnaudCore/Controllers/GarageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using ArnaudCore.Data;
using ArnaudCore.Services;
using ArnaudCore.ViewModels.Garage;

namespace ArnaudCore.Controllers
{
    public class GarageController : Controller
    {
        GarageFactory factory;
        GarageInitializer initializer;

        public GarageController(GarageFactory factory, GarageInitializer initializer)
        {
            this.factory = factory;
            this.initializer = initializer;
        }

        public IActionResult CarsList()
        {
            initializer.Initialize();
            var viewModel = new CarsListViewModel(factory.Cars);
            return View(viewModel);
        }


    }
}

DOTNET DEV/ArnaudCore/ArnaudCore/Controllers/ProductCoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ArnaudCore.Data;
using ArnaudCore.Models;

namespace ArnaudCore.Controllers
{
    public class ProductCoresController : Controller
    {
        private readonly ShopDbContext _context;

        public ProductCoresController(ShopDbContext context)
        {
            _context = context;    
        }

        // GET: ProductCores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        // GET: ProductCores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCore = await _context.Products
                .SingleOrDefaultAsync(m => m.ID == id);
            if (productCore == null)
            {
                return NotFound();
            }

            return View(productCore);
        }

        // GET: ProductCores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProductCores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description,Price,ImageName")] ProductCore productCore)
        {
            if (ModelState.IsValid)
            {
                _context.Add(productCore);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(productCore);
        }

        // GET: ProductCores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCore = await _context.Products.SingleOrDefaultAsync(m => m.ID == id);
            if (productCore == null)
            {
                return NotFound();
            }
            return View(productCore);
        }

        // POST: ProductCores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Description,Price,ImageName")] ProductCore productCore)
        {
            if (id != productCore.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productCore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductCoreExists(productCore.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(productCore);
        }

        // GET: ProductCores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCore = await _context.Products
                .SingleOrDefaultAsync(m => m.ID == id);
            if (productCore == null)
            {
                return NotFound();
            }

            return View(productCore);
        }

        // POST: ProductCores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productCore = await _context.Products.SingleOrDefaultAsync(m => m.ID == id);
            _context.Products.Remove(productCore);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ProductCoreExists(int id)
        {
            return _context.Products.Any(e => e.ID == id);
        }
    }
}

DOTNET DEV/ArnaudCore/ArnaudCore/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArnaudCore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ArnaudCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - ArnaudCore</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

DOTNET DEV/ArnaudCore/ArnaudCore/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArnaudCore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ArnaudCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Products</a></li>
                    <li><a asp-area="" asp-controller="ProductCores" asp-action="Index">Products CRUD</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Action1">File list</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="ListFiles">File list with model</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="ListFilesService">File list with service</a></li>
                    <li><a asp-area="" asp-controller="Garage" asp-action="CarsList">Cars</a></li>
                    <li><a asp-area="" asp-controller="CarCores" asp-action="Index">Cars CRUD</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="ComputeProduct">Multiply</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ArnaudCore</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>